testing before - after component
fastn-stack/fastn.com pull request #319
Opened 2023-08-24 17:51 UTC by gsalunke

@nandhinidevie Please, review the UI. @Arpita-Jaiswal requesting code review.

2023-08-25 05:34 UTC, Arpita-Jaiswal requested changes

2023-08-25 05:34 UTC, Arpita-Jaiswal commented on utils.ftd
> +optional ftd.resizing height:
```suggestion
optional caption title: 
ftd.image-src before-image: 
ftd.image-src after-image: 
optional string before-caption:
optional string after-caption:
optional ftd.resizing width:
optional ftd.resizing height:
boolean $show: false
```

2023-08-25 05:34 UTC, Arpita-Jaiswal commented on utils.ftd
> +background.solid: rgba(0,0, 0, 0.63)
```suggestion
background.solid: rgba(0, 0, 0, 0.63)
```

2023-08-25 05:34 UTC, Arpita-Jaiswal commented on utils.ftd
> +-- end: ftd.column
```suggestion
-- ds.image: $before-after.after-caption
src: $before-after.after-image
width: $before-after.width
height: $before-after.height
if: { before-after.show }
```

2023-08-25 07:41 UTC, Arpita-Jaiswal approved these changes

2023-08-26 02:21 UTC, merged

2023-08-28 04:29 UTC, nandhinidevie commented
@gsalunke the before and after effect is not correct. The reader should be able to see both before and after images at all times. When the mouse is over the before image, the after image should be visible and when is mouse is not over the image, the before image should be visible again. 
Reference: On FifthTry's team page, each member's black and white image is the default, when the mouse is over the image, the colour photo is visible, when it is not it shows b&w image only.

2023-08-28 04:43 UTC, nandhinidevie commented
The whatsapp screen suggestion for actual representation: 
Instead of Nandhini Devi, it should be ACME CEO, 
Instead of Ayush Soni, it should be a new phone number, 
the "Welcome to the Team.." message should not be from Meenu's, let's use Ajit's image and the name should be ACME VP- Marketing, 
Meenu's chat box should be different from Nandhini's, Ayush's and Ajit's chat box- Assume The Whatsapp group chat is from Meenu's phone. 
Another suggestion is to add the chat box inside an iPhone frame - see this image: https://www.pngkit.com/png/detail/776-7762990_whatsapp-features-whatsapp-in-ios-screen.png