Feature/hero components
fastn-stack/fastn.com pull request #343
Opened 2023-08-31 13:14 UTC by saurabh-lohiya

2023-08-31 13:54 UTC, gsalunke requested changes

2023-08-31 13:54 UTC, gsalunke commented on featured/sections/heros/index.ftd
> +more-link: /featured/sections/heros/hero/
```suggestion
more-link: /featured/heros/
```

2023-08-31 13:54 UTC, gsalunke commented on featured/sections/heros/index.ftd
> +template-url: featured/sections/heros/hero-bottom-hug/
```suggestion
template-url: /hero-bottom-hug/
```

2023-08-31 13:54 UTC, gsalunke commented on featured/sections/heros/index.ftd
> +template-url: featured/sections/heros/hero-bottom-hug-search/
```suggestion
template-url: /hero-bottom-hug-search/
```

2023-08-31 13:54 UTC, gsalunke commented on featured/sections/heros/index.ftd
> +template-url: featured/sections/heros/hero-left-hug-expanded-search/
```suggestion
template-url: /hero-left-hug-expanded-search/
```

2023-08-31 13:54 UTC, gsalunke commented on featured/sections/heros/index.ftd
> +template-url: featured/sections/heros/hero-left-hug-expanded/
```suggestion
template-url: /hero-left-hug-expanded/
```

2023-08-31 13:54 UTC, gsalunke commented on featured/sections/heros/index.ftd
> +template-url: featured/sections/heros/hero-right-hug-expanded-search/
```suggestion
template-url: /hero-right-hug-expanded-search/
```
@saurabh-lohiya change others accordingly.

2023-08-31 13:54 UTC, gsalunke commented on images/featured/components/hero-bottom-hug-search.jpg
@saurabh-lohiya the buttons not looking good. Apply a color scheme to your package and then take screenshots with proper colors applied to all buttons.

2023-09-01 06:54 UTC, saurabh-lohiya commented on images/featured/components/hero-bottom-hug-search.jpg
@gsalunke should I take screenshot of this?
https://saurabh-lohiya.github.io/hero/docs/hero-right-hug-search/
and accordingly

2023-09-14 09:12 UTC, merged