fix: Replaced /clean-url/ to /clean-url/-/build/ for How to create clean URLs.
fastn-stack/fastn.com pull request #460
Opened 2023-10-06 18:05 UTC by apneduniya

For more reference have a look at https://github.com/fastn-stack/fastn/issues/1374

2023-10-06 18:06 UTC, harshdoesdev commented
Yo, @gargajit, could you please review this PR?

2023-10-06 19:04 UTC, Arpita-Jaiswal requested changes

2023-10-06 19:04 UTC, Arpita-Jaiswal commented on expander/ds/understanding-sitemap.ftd
> +[`How to create clean URLs`](/clean-urls/-/build/).
Don't change the URL here instead go to `FASTN.ftd` file and change the url there from `/clean-urls/-/build/` to `/clean-urls/`

2023-10-07 08:10 UTC, Arpita-Jaiswal commented
@apneduniya You have to change the URL in acme.ftd too and please check if there's any other file. Also add redirect entry in FASTN.ftd

```ftd
-- fastn.redirects:

/clean-urls/-/build/ -> /clean-urls/
...
```

So that the previous link doesn't fail.

2023-10-07 13:54 UTC, gargajit approved these changes

2023-10-07 13:55 UTC, Arpita-Jaiswal approved these changes

2023-10-07 13:55 UTC, merged